# 3. queries.sql

-- =========================================
-- BASIC QUERIES
-- =========================================

-- Display all customers

SELECT * FROM customers;


-- Show all available food items

SELECT item_name, price, category
FROM menu_items
WHERE availability_status = 'Available';


-- Restaurants with high ratings

SELECT restaurant_name, location, rating
FROM restaurants
WHERE rating > 4.2;


-- Orders sorted by total amount

SELECT order_id, total_amount, order_status
FROM orders
ORDER BY total_amount DESC;


-- Top 3 expensive food items

SELECT item_name, price
FROM menu_items
ORDER BY price DESC
LIMIT 3;


-- Customers located in Pune

SELECT name, email, address
FROM customers
WHERE address = 'Pune';


-- Display delivered orders

SELECT order_id, order_status, total_amount
FROM orders
WHERE order_status = 'Delivered';


-- Food items within price range

SELECT item_name, price
FROM menu_items
WHERE price BETWEEN 100 AND 300;


-- Restaurants starting with letter S

SELECT restaurant_name
FROM restaurants
WHERE restaurant_name LIKE 'S%';


-- Display all food categories

SELECT DISTINCT category
FROM menu_items;


-- =========================================
-- JOIN QUERIES
-- =========================================

-- Customers and their orders

SELECT
    c.customer_id,
    c.name,
    o.order_id,
    o.order_status,
    o.total_amount
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id;


-- Restaurants with their food items

SELECT
    r.restaurant_name,
    m.item_name,
    m.price,
    m.category
FROM restaurants r
INNER JOIN menu_items m
ON r.restaurant_id = m.restaurant_id;


-- Orders and payment information

SELECT
    o.order_id,
    o.total_amount,
    p.payment_method,
    p.payment_status
FROM orders o
INNER JOIN payments p
ON o.order_id = p.order_id;


-- Orders with delivery partner details

SELECT
    o.order_id,
    o.order_status,
    d.partner_name,
    d.vehicle_type
FROM orders o
INNER JOIN delivery_partners d
ON o.delivery_partner_id = d.partner_id;


-- Customer reviews for restaurants

SELECT
    c.name AS customer_name,
    r.restaurant_name,
    rv.rating,
    rv.comment
FROM reviews rv
INNER JOIN customers c
ON rv.customer_id = c.customer_id
INNER JOIN restaurants r
ON rv.restaurant_id = r.restaurant_id;


-- Complete order details

SELECT
    o.order_id,
    c.name AS customer_name,
    r.restaurant_name,
    m.item_name,
    oi.quantity,
    oi.subtotal
FROM order_items oi
INNER JOIN orders o
ON oi.order_id = o.order_id
INNER JOIN customers c
ON o.customer_id = c.customer_id
INNER JOIN menu_items m
ON oi.item_id = m.item_id
INNER JOIN restaurants r
ON m.restaurant_id = r.restaurant_id;


-- Restaurants and their reviews

SELECT
    r.restaurant_name,
    rv.rating,
    rv.comment
FROM restaurants r
LEFT JOIN reviews rv
ON r.restaurant_id = rv.restaurant_id;


-- Customers with payment details

SELECT
    c.name,
    o.order_id,
    p.payment_status
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN payments p
ON o.order_id = p.order_id;


-- Delivery partners handling completed deliveries

SELECT
    d.partner_name,
    o.order_id,
    o.order_status
FROM delivery_partners d
INNER JOIN orders o
ON d.partner_id = o.delivery_partner_id
WHERE o.order_status = 'Delivered';


-- Food items ordered by customers

SELECT
    c.name,
    m.item_name,
    oi.quantity
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN order_items oi
ON o.order_id = oi.order_id
INNER JOIN menu_items m
ON oi.item_id = m.item_id;


-- =========================================
-- AGGREGATE FUNCTIONS + GROUP BY + HAVING
-- =========================================

-- Total number of customers

SELECT COUNT(*) AS total_customers
FROM customers;


-- Total revenue from all delivered orders

SELECT SUM(total_amount) AS total_revenue
FROM orders
WHERE order_status = 'Delivered';


-- Average restaurant rating

SELECT AVG(rating) AS average_rating
FROM restaurants;


-- Most expensive menu item

SELECT item_name, price
FROM menu_items
WHERE price = (
    SELECT MAX(price)
    FROM menu_items
);


-- Number of orders placed by each customer

SELECT
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name;


-- Revenue generated by each restaurant

SELECT
    r.restaurant_name,
    SUM(oi.subtotal) AS total_revenue
FROM restaurants r
INNER JOIN menu_items m
ON r.restaurant_id = m.restaurant_id
INNER JOIN order_items oi
ON m.item_id = oi.item_id
GROUP BY r.restaurant_name;


-- Most ordered menu items

SELECT
    m.item_name,
    SUM(oi.quantity) AS total_quantity_ordered
FROM menu_items m
INNER JOIN order_items oi
ON m.item_id = oi.item_id
GROUP BY m.item_name
ORDER BY total_quantity_ordered DESC;


-- Restaurants with high average ratings

SELECT
    restaurant_name,
    rating
FROM restaurants
WHERE rating > 4.3;


-- Number of orders by status

SELECT
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;


-- Customers with multiple orders

SELECT
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING COUNT(o.order_id) > 1;


-- =========================================
-- SUBQUERIES
-- =========================================

-- Most expensive food item

SELECT item_name, price
FROM menu_items
WHERE price = (
    SELECT MAX(price)
    FROM menu_items
);


-- Customers with order amount above average

SELECT order_id, customer_id, total_amount
FROM orders
WHERE total_amount > (
    SELECT AVG(total_amount)
    FROM orders
);


-- Restaurant with highest rating

SELECT restaurant_name, rating
FROM restaurants
WHERE rating = (
    SELECT MAX(rating)
    FROM restaurants
);


-- Orders above average total amount

SELECT order_id, total_amount
FROM orders
WHERE total_amount > (
    SELECT AVG(total_amount)
    FROM orders
);


-- Customer with maximum number of orders

SELECT customer_id, COUNT(order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(order_id) = (
    SELECT MAX(order_count)
    FROM (
        SELECT COUNT(order_id) AS order_count
        FROM orders
        GROUP BY customer_id
    ) AS temp
);


-- =========================================
-- ADVANCED REPORT QUERIES
-- =========================================

-- Top 3 restaurants by revenue

SELECT
    r.restaurant_name,
    SUM(oi.subtotal) AS total_revenue
FROM restaurants r
INNER JOIN menu_items m
ON r.restaurant_id = m.restaurant_id
INNER JOIN order_items oi
ON m.item_id = oi.item_id
GROUP BY r.restaurant_name
ORDER BY total_revenue DESC
LIMIT 3;


-- Most ordered food items

SELECT
    m.item_name,
    SUM(oi.quantity) AS total_quantity_ordered
FROM menu_items m
INNER JOIN order_items oi
ON m.item_id = oi.item_id
GROUP BY m.item_name
ORDER BY total_quantity_ordered DESC;


-- Payment status report

SELECT
    payment_status,
    COUNT(*) AS total_payments
FROM payments
GROUP BY payment_status;


-- Delivered and cancelled orders report

SELECT
    order_status,
    COUNT(*) AS total_orders
FROM orders
WHERE order_status IN ('Delivered', 'Cancelled')
GROUP BY order_status;


-- Average food price by restaurant

SELECT
    r.restaurant_name,
    AVG(m.price) AS average_food_price
FROM restaurants r
INNER JOIN menu_items m
ON r.restaurant_id = m.restaurant_id
GROUP BY r.restaurant_name;


-- =========================================
-- VIEWS
-- =========================================

-- View for active orders

CREATE VIEW active_orders_view AS
SELECT
    order_id,
    customer_id,
    order_status,
    total_amount
FROM orders
WHERE order_status IN ('Pending', 'Out for Delivery');


-- View for restaurant revenue

CREATE VIEW restaurant_revenue_view AS
SELECT
    r.restaurant_name,
    SUM(oi.subtotal) AS total_revenue
FROM restaurants r
INNER JOIN menu_items m
ON r.restaurant_id = m.restaurant_id
INNER JOIN order_items oi
ON m.item_id = oi.item_id
GROUP BY r.restaurant_name;


-- View for customer order history

CREATE VIEW customer_order_history_view AS
SELECT
    c.name AS customer_name,
    o.order_id,
    o.order_status,
    o.total_amount
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id;


-- =========================================
-- STORED PROCEDURES
-- =========================================

DELIMITER //

CREATE PROCEDURE GetOrdersByStatus(
    IN input_status VARCHAR(30)
)
BEGIN

    SELECT
        order_id,
        customer_id,
        order_status,
        total_amount
    FROM orders
    WHERE order_status = input_status;

END //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE GetRestaurantMenu(
    IN input_restaurant_id INT
)
BEGIN

    SELECT
        item_name,
        price,
        category
    FROM menu_items
    WHERE restaurant_id = input_restaurant_id;

END //

DELIMITER ;


-- =========================================
-- TRIGGERS
-- =========================================

DELIMITER //

CREATE TRIGGER update_order_total
AFTER INSERT ON order_items
FOR EACH ROW
BEGIN

    UPDATE orders
    SET total_amount = (
        SELECT SUM(subtotal)
        FROM order_items
        WHERE order_id = NEW.order_id
    )
    WHERE order_id = NEW.order_id;

END //

DELIMITER ;


-- =========================================
-- INDEXES
-- =========================================

CREATE INDEX idx_customer_email
ON customers(email);


CREATE INDEX idx_order_status
ON orders(order_status);
